repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: ^src/rio_tiler_pds_sentinel_utils_orig.py
        language_version: python
        args: [--line-length, "120"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        language_version: python
        args: [--profile=black]

  - repo: https://github.com/PyCQA/flake8
    # 6.0.0 requires python 3.8.1 or later
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python

  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 5.1.1
  #   hooks:
  #     - id: pydocstyle
  #       language_version: python

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        exclude: ^src/rio_tiler_pds_sentinel_utils(_orig)*.py
        language_version: python
        # pass_filenames: false
        args: [--exclude, 'rio_tiler_pds_sentinel_utils.*\.py']
